Repository TakwimuAfrica/Dashboard, pull requests merged in 2019-11, with the labels that each got.

#17 Use WP_REST_Response
  wp-content/plugins/hurumap/.eslintrc.js
  wp-content/plugins/hurumap/api.php
  wp-content/plugins/hurumap/index.php
  wp-content/plugins/hurumap/package.json
  wp-content/plugins/hurumap/src/App.js
  wp-content/plugins/hurumap/src/FlourishBlock/Chart.js
  wp-content/plugins/hurumap/src/FlourishChart.js
  wp-content/plugins/hurumap/src/HURUmapBlock/Chart.js
  wp-content/plugins/hurumap/yarn.lock
  wp-content/themes/hurumap/assets/js/config-flourish.js
Labels: bug

#20 [Hotfix] Store Visual customizations in typeProps
  wp-content/plugins/hurumap/package.json
  wp-content/plugins/hurumap/src/HurumapChart.js
  wp-content/plugins/hurumap/yarn.lock
Labels: bug, enhancement

#19 Flourish Chart Description & Insight chart Analysis Content
  wp-content/plugins/hurumap/api.php
  wp-content/plugins/hurumap/db.php
  wp-content/plugins/hurumap/package.json
  wp-content/plugins/hurumap/src/FeaturedData/Edit.js
  wp-content/plugins/hurumap/src/FlourishBlock/Chart.js
  wp-content/plugins/hurumap/src/FlourishBlock/Edit.js
  wp-content/plugins/hurumap/src/FlourishBlock/Save.js
  wp-content/plugins/hurumap/src/FlourishBlock/index.js
  wp-content/plugins/hurumap/src/FlourishChart.js
  wp-content/plugins/hurumap/src/HURUmapBlock/Chart.js
  wp-content/plugins/hurumap/src/HURUmapBlock/EditChart.js
  wp-content/plugins/hurumap/src/HURUmapBlock/SaveChart.js
  wp-content/plugins/hurumap/src/HURUmapBlock/index.js
  wp-content/plugins/hurumap/src/Theme.js
  wp-content/plugins/hurumap/yarn.lock
Labels: enhancement

#22 Remove title from featured data inner-content
  wp-content/plugins/hurumap/src/FeaturedData/Edit.js
  wp-content/plugins/hurumap/src/FeaturedData/index.js
  wp-content/plugins/hurumap/src/HURUmapBlock/index.js
Labels: bug

#23 [Hotfix] production ENV name
  package.json
Labels: bug

#26 Update README file
  README.md
Labels: documentation

#21 Hurumap Chart description & Sources
  wp-content/plugins/hurumap/db.php
  wp-content/plugins/hurumap/package.json
  wp-content/plugins/hurumap/src/Chart.js
  wp-content/plugins/hurumap/src/FlourishBlock/Chart.js
  wp-content/plugins/hurumap/src/HURUmapBlock/Chart.js
  wp-content/plugins/hurumap/src/HURUmapBlock/EditChart.js
  wp-content/plugins/hurumap/src/HurumapChart.js
  wp-content/plugins/hurumap/src/HurumapChartPreview.js
  wp-content/plugins/hurumap/src/data/queries.js
Labels: enhancement

#25 Chart section ordering
  wp-content/plugins/hurumap/api.php
  wp-content/plugins/hurumap/db.php
  wp-content/plugins/hurumap/package.json
  wp-content/plugins/hurumap/src/App.js
  wp-content/plugins/hurumap/src/ChartsSection.js
  wp-content/plugins/hurumap/src/api.js
Labels: enhancement

#27 Use iframe onload + other bugs
  wp-content/plugins/hurumap/api.php
  wp-content/plugins/hurumap/src/FlourishBlock/Edit.js
  wp-content/plugins/hurumap/src/HURUmapBlock/EditChart.js
  wp-content/plugins/hurumap/src/HurumapChartPreview.js
  wp-content/themes/hurumap/assets/js/config-flourish.js
  wp-content/themes/hurumap/functions.php
Labels: bug
