Repository TakwimuAfrica/Dashboard, pull requests merged in 2020-01, with the labels that each got.

#33 [Hotfix] HURUmap charts id hydration & comparison
  wp-content/plugins/hurumap/src/HURUmapBlock/Chart.js
  wp-content/plugins/hurumap/src/HURUmapBlock/EditChart.js
  wp-content/plugins/hurumap/src/micro-frontend/hurumap-ui-blocks.js
  wp-content/plugins/hurumap/yarn.lock
Labels: bug

#34 Fix hurumap-visual indexability + cleanup
  wp-content/plugins/hurumap/data.php
  wp-content/themes/hurumap/functions.php
Labels: bug, enhancement

#35 Exclude site pages from search results
  wp-content/themes/hurumap/functions.php
Labels: bug, enhancement

#37 Table source relation
  wp-content/plugins/hurumap/src/ChartDefinition/HurumapChart.js
  wp-content/plugins/hurumap/src/HURUmapBlock/Chart.js
  wp-content/plugins/hurumap/src/data/queries.js
  wp-content/plugins/hurumap/src/data/sources.sql
Labels: enhancement

#39 [Hotfix] Add description below to indicator widget
  wp-content/themes/hurumap/template-parts/blocks/indicator.php
Labels: bug

#40 [Hotfix] Remove geography custom fields
  wp-content/themes/hurumap/acf-json/group_5d91f54751c13.json
  wp-content/themes/hurumap/functions.php
Labels: enhancement

#42 [Hotfix] Fix HURUmap Chart Hydration
  wp-content/plugins/hurumap/src/micro-frontend/hurumap-ui-blocks.js
Labels: bug

#43 [Hotfix] Indicator description styling
  wp-content/themes/hurumap/template-parts/blocks/indicator.php
Labels: bug

#44 Feature post type modal
  wp-content/plugins/hurumap/package.json
  wp-content/plugins/hurumap/src/Actions.js
  wp-content/plugins/hurumap/src/ChartDefinition/ChartDefinition.js
  wp-content/plugins/hurumap/src/FlourishBlock/Edit.js
  wp-content/plugins/hurumap/src/HURUmapBlock/Chart.js
  wp-content/plugins/hurumap/src/HURUmapBlock/EditChart.js
  wp-content/plugins/hurumap/src/PostModal.js
  wp-content/plugins/hurumap/src/hooks/useFilteredCharts.js
  wp-content/plugins/hurumap/src/hooks/useGeos.js
  wp-content/plugins/hurumap/yarn.lock
Labels: enhancement

#47 [Hotfix] Hide snippets + inGeographies for hurumap chart
  wp-content/plugins/hurumap/posttypes.php
  wp-content/plugins/hurumap/src/ChartDefinition/HurumapChart.js
  wp-content/plugins/hurumap/src/GeoSelect.js
Labels: bug

#48 [HotFix] Update `content` acf field
  wp-content/themes/hurumap/acf-json/group_5d91c40e5c4ac.json
Labels: bug

#49 [HotFix] Flourish zip upload on windows
  wp-content/plugins/hurumap/package.json
  wp-content/plugins/hurumap/src/ChartDefinition/FlourishChart.js
  wp-content/plugins/hurumap/yarn.lock
Labels: bug

#50 [HotFix] Window flourish zip 2
  wp-content/plugins/hurumap/api.php
  wp-content/plugins/hurumap/src/ChartDefinition/FlourishChart.js
Labels: bug

#51 [Fix] Analysis/Data by Topic selector
  wp-content/themes/hurumap/acf-json/group_5e26f8a49b739.json
Labels: bug

#52 [HotFix] Add property to in topics
  wp-content/plugins/hurumap/index.php
  wp-content/plugins/hurumap/utils.php
Labels: bug
